## Diabetes Prediction

Diabetes prediction refers to the process of using various data, such as medical records, demographic information, lifestyle factors, and genetic predispositions, to predict the likelihood of an individual developing diabetes in the future. Machine learning techniques are commonly used for diabetes prediction. These techniques involve training a model on historical data of individuals who have been diagnosed with diabetes or have risk factors for diabetes, and then using this trained model to make predictions on new, unseen data.

The following steps are followed,

* Import Library
* Load the diabetes dataset
* Split the data into 6 files
* Save the data files
* Define the model
* Define the pipeline
* Train the models
* Save the model
* Evaluate the model on the training set

#### Import Library

In [202]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE
from sklearn.pipeline import make_pipeline
from joblib import dump, load

import pickle

#### Reading the dataset

In [204]:
diabetes_df = pd.read_csv('diabetes.csv')

In [205]:
diabetes_df.head()

,Index,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,0,6,148,72,35,0,33.6,0.627,50,1
1,1,1,85,66,29,0,26.6,0.351,31,0
2,2,8,183,64,0,0,23.3,0.672,32,1
3,3,1,89,66,23,94,28.1,0.167,21,0
4,4,0,137,40,35,168,43.1,2.288,33,1

In [206]:
diabetes_df.sample(20)

,Index,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
560,560,6,125,76,0,0,33.8,0.121,54,1
68,68,1,95,66,13,38,19.6,0.334,25,0
683,683,4,125,80,0,0,32.3,0.536,27,1
468,468,8,120,0,0,0,30.0,0.183,38,1
697,697,0,99,0,0,0,25.0,0.253,22,0
2,2,8,183,64,0,0,23.3,0.672,32,1
587,587,6,103,66,0,0,24.3,0.249,29,0
429,429,1,95,82,25,180,35.0,0.233,43,1
63,63,2,141,58,34,128,25.4,0.699,24,0
149,149,2,90,70,17,0,27.3,0.085,22,0
121,121,6,111,64,39,0,34.2,0.260,24,0
365,365,5,99,54,28,83,34.0,0.499,30,0
312,312,2,155,74,17,96,26.6,0.433,27,1
723,723,5,117,86,30,105,39.1,0.251,42,0
266,266,0,138,0,0,0,36.3,0.933,25,1
148,148,5,147,78,0,0,33.7,0.218,65,0
496,496,5,110,68,0,0,26.0,0.292,30,0
483,483,0,84,82,31,125,38.2,0.233,23,0
146,146,9,57,80,37,0,32.8,0.096,41,0
664,664,6,115,60,39,0,33.7,0.245,40,1

In [207]:
diabetes_df.shape

(772, 10)

In [208]:
diabetes_df.describe(include='all')

,Index,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,772.000000,772.000000,772.000000,772.000000,772.000000,772.000000,772.000000,772.000000,772.000000,772.000000
mean,385.479275,3.836788,120.866580,69.099741,20.534974,79.531088,31.986788,0.471049,33.233161,0.348446
std,222.965942,3.364851,31.905935,19.308651,15.934368,115.057930,7.868856,0.330680,11.748667,0.476787
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,192.750000,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.244000,24.000000,0.000000
50%,385.500000,3.000000,117.000000,72.000000,23.000000,27.000000,32.000000,0.370000,29.000000,0.000000
75%,578.250000,6.000000,140.000000,80.000000,32.000000,126.250000,36.600000,0.624500,41.000000,1.000000
max,767.000000,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [209]:
diabetes_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 772 entries, 0 to 771
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Index                     772 non-null    int64
 1   Pregnancies               772 non-null    int64
 2   Glucose                   772 non-null    int64
 3   BloodPressure             772 non-null    int64
 4   SkinThickness             772 non-null    int64
 5   Insulin                   772 non-null    int64
 6   BMI                       772 non-null    float64
 7   DiabetesPedigreeFunction  772 non-null    float64
 8   Age                       772 non-null    int64
 9   Outcome                   772 non-null    int64
dtypes: float64(2), int64(8)
memory usage: 60.4 KB

In [210]:
diabetes_df.duplicated().value_counts()

False    768
True       4
Name: count, dtype: int64

In [211]:
diabetes_df.drop_duplicates()

,Index,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,0,6,148,72,35,0,33.6,0.627,50,1
1,1,1,85,66,29,0,26.6,0.351,31,0
2,2,8,183,64,0,0,23.3,0.672,32,1
3,3,1,89,66,23,94,28.1,0.167,21,0
4,4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...,...
763,763,10,101,76,48,180,32.9,0.171,63,0
764,764,2,122,70,27,0,36.8,0.340,27,0
765,765,5,121,72,23,112,26.2,0.245,30,0
766,766,1,126,60,0,0,30.1,0.349,47,1
767,767,1,93,70,31,0,30.4,0.315,23,0

In [212]:
diabetes_df.isnull().value_counts()

Index  Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI    DiabetesPedigreeFunction  Age    Outcome
False  False        False    False          False          False    False  False                     False  False      772
Name: count, dtype: int64

In [213]:
diabetes_df.isnull().sum()

Index                       0
Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

#### Separate Features and Target variable

In [214]:
X = diabetes_df.drop('Outcome', axis=1)
y = diabetes_df['Outcome']

#### Split the data

In [215]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.40, random_state=123)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.50, random_state=123)

#### Save the data

In [216]:
X_train.to_csv('Data/X_train.csv', index=False)
X_test.to_csv('Data/X_test.csv', index=False)
y_train.to_csv('Data/y_train.csv', index=False)
y_test.to_csv('Data/y_test.csv', index=False)
X_val.to_csv('Data/X_val.csv', index=False)
y_val.to_csv('Data/y_val.csv', index=False)

In [217]:
print(X_train.shape,X_test.shape,X_val.shape,y_train.shape,y_test.shape,y_val.shape)

(231, 9) (309, 9) (232, 9) (231,) (309,) (232,)

In [218]:
X_train

,Index,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
191,191,9,123,70,44,94,33.1,0.374,40
582,582,12,121,78,17,0,26.5,0.259,62
675,675,6,195,70,0,0,30.9,0.328,31
197,197,3,107,62,13,48,22.9,0.678,23
451,451,2,134,70,0,0,28.9,0.542,23
...,...,...,...,...,...,...,...,...,...
238,238,9,164,84,21,0,30.8,0.831,32
429,429,1,95,82,25,180,35.0,0.233,43
8,8,2,197,70,45,543,30.5,0.158,53
56,56,7,187,68,39,304,37.7,0.254,41
467,467,0,97,64,36,100,36.8,0.600,25

In [219]:
y_train

191    0
582    0
675    1
197    1
451    1
      ..
238    1
429    1
8      1
56     1
467    0
Name: Outcome, Length: 231, dtype: int64

#### Define the models

In [220]:
models = [
    ('Decision Tree', DecisionTreeClassifier()),
    ('Random Forest', RandomForestClassifier()),
    ('Logistic Regression', LogisticRegression())
]

# Define the pipeline
pipeline = make_pipeline(StandardScaler(), RFE(estimator=LogisticRegression(), n_features_to_select=3))

# Train and save each model
for name, model in models:
    pipeline.set_params(rfe__estimator=model, rfe__n_features_to_select=3)
    pipeline.fit(X_train, y_train)
    acc = pipeline.score(X_val, y_val)
    print(f'{name} accuracy on validation set: {acc:.2%}')
    
    # Save the model
    with open(f'{name}_model.pkl', 'wb') as f:
        pickle.dump(pipeline, f)

# Load the saved model
with open('Decision Tree_model.pkl', 'rb') as f:
    decision_tree_model = pickle.load(f)

with open('Random Forest_model.pkl', 'rb') as f:
    random_forest_model = pickle.load(f)

with open('Logistic Regression_model.pkl', 'rb') as f:
    logistic_regression_model = pickle.load(f)

Decision Tree accuracy on validation set: 64.66%
Random Forest accuracy on validation set: 68.53%
Logistic Regression accuracy on validation set: 71.98%